---

- name: Install ntp
  apt: name=ntp state=present update-cache=yes
  become: true

- name: Ensure ntp's configuration files exist
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item | basename | regex_replace('.j2','') }}"
  with_items:
    - ntp.conf.j2
  become: true

- name: Restart ntp server
  service: name=ntp state=restarted
  become: true
