---

- include_vars: vars.yml

- name: Test if Spark is functioning by running a Pi calculation.
  command: spark-submit --class org.apache.spark.examples.SparkPi \
    --master yarn \
    --deploy-mode cluster \
    --driver-memory 2g \
    --executor-memory 1g \
    --executor-cores 1 \
    {{ spark_home }}/examples/jars/spark-examples_2.11-2.0.2.jar \
    2
  environment: "{{ spark_env }}"
  register: result
- debug: msg={{ result }}

